### PR TITLE
Updates Gemlock to 2.2.1

### PR DESCRIPTION
**Pull request by adamzinder**
bumps_version_2_2_1

### CODE REVIEW

**Review by robframpton — APPROVED** [review]

**Comment by robframpton** [comment]
Actually looks like we need to update the version in lib/workos/version.rb as well.

**Comment by mthadley** [comment]
Should we wait until #148 is merged before merging this version bump?

That way we don't have two version bumps super close together.

**Comment by ams11** [comment]
> Should we wait until https://github.com/workos/workos-ruby/pull/148 is merged before merging this version bump?

> That way we don't have two version bumps super close together.

There's going to be a small followup to https://github.com/workos/workos-ruby/pull/148 coming as well, would love to wait to include both of those in the next version 🙏

**Comment by ams11** [comment]
I went ahead and opened https://github.com/workos/workos-ruby/pull/154 to create a new gem version, now that #148 and #152 are in (I also forgot that we already had this PR open 🤦). Do we have any preferences between updating this PR with the latest changes in `main` or just going ahead with #154? I'm happy to go with either one...

**Comment by adamzinder** [comment]
@ams11 feel free to move forward with #154.  I'll close this one out!

**Pull request closed without merging**
